# These are supported funding model platforms

github: ProgrammerNomad # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: NomadProgrammer # Replace with a single Patreon username
open_collective: NomadProgrammer # Replace with a single Open Collective username
ko_fi: NomadProgrammer # Replace with a single Ko-fi username
tidelift: NomadProgrammer # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: NomadProgrammer # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: NomadProgrammer # Replace with a single Liberapay username
issuehunt: NomadProgrammer # Replace with a single IssueHunt username
otechie: NomadProgrammer # Replace with a single Otechie username
