# These are supported funding model platforms

github: ProgrammerNomad # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: NomadProgrammer # Replace with a single Patreon username
open_collective: NomadProgrammer # Replace with a single Open Collective username
