[context.production.environment]
  HUGO_VERSION = "0.82.1"
  
[[plugins]]
package = "netlify-deployment-hours-plugin"

  [plugins.inputs]
  # Optional: a comma-separated list of deploy contexts this plugin should monitor (default: "production")
  contexts = "production"   # default value
  # A cron-like expression that expresses when a deployment can occur
  expression = "* */3 * * *"
  # tz database value that expresses the timezone of the expression
  timezone = "America/Toronto"

[[headers]]
    for = "/*.json"
    [headers.values]
        Access-Control-Allow-Origin = "*"
